version: '3.1'

services:
  socat:
    image: jmb12686/socat
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: [ "socat", "tcp-listen:2375,fork,reuseaddr","unix-connect:/var/run/docker.sock" ]

  redis:
    image: redis:alpine
    restart: always
    logging:
      driver: none
    ports:
      - "192.168.6.1:6379:6379"

  mysql:
    image: mysql:5.7
    restart: always
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    logging:
      driver: none
    ports:
      - "192.168.6.1:3306:3306"

  ytdl:
    image: bennythink/ytdlbot
    env_file:
      - env/ytdl.env
    restart: always
    depends_on:
      - socat
      - redis
    volumes:
      - ./data/instagram.com_cookies.txt:/ytdlbot/ytdlbot/instagram.com_cookies.txt
      - ./data/vnstat/:/var/lib/vnstat/
